[package]
name = "blog_os"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.1.0"
rlibc = "1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"